### PR TITLE
refactor/idiomatic-go

### PR DESCRIPTION
**Pull request by GalvinGao**
The effort is to lay down a better future path for the v3 api development. To better distinguish different `struct`s and `interface`s of APIs, a better way than simple `shims` should be implemented.

This change has fixed some naming based on naming conventions from 
- [Effective Go](https://go.dev/doc/effective_go)
- The [kubernetes](https://github.com/kubernetes/kubernetes) code repo: they do have a huge codebase consisting of type definitions for different API versions, as well for feature gates which are hard to done right without any guidance.
- [Idiomatic Go (community)](https://dmitri.shuralyov.com/idiomatic-go)

### CODE REVIEW

**Review by FlandiaYingman — CHANGES_REQUESTED** [review]
How about replace:
```
fx.Invoke(controllermeta.RegisterMeta),
fx.Invoke(controllermeta.RegisterIndex),
fx.Invoke(controllermeta.RegisterAdmin),
// ...
```
with: 
```
fx.Invoke(
  controllermeta.RegisterMeta,
  controllermeta.RegisterIndex,
  controllermeta.RegisterAdmin,
  // ...
)
```

It's clearer and more idiomatic

**Comment by GalvinGao** [comment]
> How about replace:
> 
> ```
> fx.Invoke(controllermeta.RegisterMeta),
> fx.Invoke(controllermeta.RegisterIndex),
> fx.Invoke(controllermeta.RegisterAdmin),
> // ...
> ```
> 
> with:
> 
> ```
> fx.Invoke(
>   controllermeta.RegisterMeta,
>   controllermeta.RegisterIndex,
>   controllermeta.RegisterAdmin,
>   // ...
> )
> ```
> 
> It's clearer and more idiomatic

Nice catch. I didn't noticed that [`fx.Invoke`](https://pkg.go.dev/go.uber.org/fx#Invoke) can be passed with multiple args

**Comment by GalvinGao** [comment]
https://github.com/penguin-statistics/backend-next/pull/38#pullrequestreview-933123999 fixed in [`576b66b` (#38)](https://github.com/penguin-statistics/backend-next/pull/38/commits/576b66bd01b47c9674936c177dd286a98bf397d9)

**Comment by FlandiaYingman** [comment]
Hey Galvin, 

I noticed that the "Repo", "Service" and "Controller" suffixes are removed. Seems you're finding a way to better structure and organize the package and code layout. Hence, I would like to introduce "Organize Packages by Responsibility" principle to you. 

That is, in brief, don't do `model.Item`, `repo.Item` or `service.Item`, but do `item.Model`, `item.Repo` and `item.Service`. Why? Because Go is different from Java in the view of packages.

So, what are the advances? Here's some examples of `Item`.

#### Human Readability

`item.Repo` is good, because we know that's the repository of the `item` entity.

`repo.Item` is (at least in my view) slightly ambiguous, because it could refer to both - an item in repository (like, rows in SQL), and repository of the `item` entity.

#### App Scaling

If more functionalities are being added to the app, the "generic" package like `repo`, `service` or `model` will grow rapidly. And finally, we get huge "generic" packages. That's a (kind of) vertical scaling, but we might prefer a horizontal scaling, since it provides more expansibility.

#### Member Visibility

There's no reason that `model.Account` can access `model.Item`'s private members (if they have). 

But it makes sense when `item.Service` can access a private `item.repo`. Since `repo.Item` was only used in `service.Item` in the code, so it is reasonable that turn item repo into a private (unexported) member, making it only accessible to item service.

With the principle, we don't need to export every repository or service to global. We can make them private selectively if we don't need them.

#### Others

Sub packages like `controller/meta` are annoying (especially we have to always give it an alias `controllermeta`). How do we know a `meta.Meta` is actually a controller? 

### Conclusion

With the "Organize Packages by Responsibility" principle, it's easier to write more semantic, specific and conventional code.

However, if you feel comfortable with the existing layout. Just let it be as it is. Principles are only the best when it suits.

### Further Readings

https://rakyll.org/style-packages/#organize-by-responsibility
https://dave.cheney.net/practical-go/presentations/gophercon-israel.html#packages
https://github.com/danceyoung/paper-code/blob/master/package-style-guideline/packagestyleguideline.md

**Comment by GalvinGao** [comment]
@FlandiaYingman Thanks for bringing this up - I actually thought of this before but for some reasons it just slipped through my head and I ended up with the k8s-like naming layout. I really like the point it could improve isolation for member visibility in which in the current design, such visibility is just not existing - they are placed in a way that it seems they are isolated - but in compiler's mind it's not and could create potential problems in the future.

I would be glad to implement such layout instead of the current one. Currently the largest blocking issue before we could move on to v3 is to organize the project structure so it is suitable for future development.

There's one more problem I wanna rise up to this discussion before I could move on implementing this structure is that, how can we then distinguish `v2` and `v3` responsibilities?

One of the ways is to declare the api version at the parent of the responsibility namespace. That is, to use `.../v2/item` and `.../v3/item`. However, this leaves a flaw in which the common DB model definition (the one containing `bun.BaseModel`) has to be:
1. duplicated into different versions, as `".../v2/item".Model`, `".../v3/item".Model`, or
2. placed in a "special" version, as `".../common/item".Model`, or
3. placed in a responsibility-agnostic package, as potentially `"github.com/penguin-statistics/backend-next/internal/model".Item`

In the sake of splitting responsibilities, I would prefer the 2nd approach. However there might be other better ways to accomplish this so approaches on how to place common declarations is open to discussion.

**Comment by FlandiaYingman** [comment]
Hey @GalvinGao,

我的第一个想法是，把 `v2` 想象成 `v3` 的兼容层。把所有实现放在 `v3` 的包里，然后让 v2 依赖于 v3 的实现。这样做的原因是， v3 和 v2 的地位不是平等的，新功能肯定会放在 v3 里，而 v2 在未来的某一天是会被弃用的。这样做的好处是，开发时我们只需专注于最新的实现，并且这样一来， **v2 和 v3 公用的部分我们就放在 v3 里就可以了。**

大概像这样：

```
┌───────────────────┬──────────────┐
│ItemController(V2)◄│Item(EntityV2)◄─┐
└───────────────────┴──────────────┘ │
┌───────────────────┬─────────────┬──┴─────────┬──────────┬────────┐
│ItemController(V3)◄│Item(Entity)◄│ItemService◄│ItemModel◄│ItemRepo│
└───────────────────┴─────────────┴────────────┴──────────┴────────┘
```

当然如果 v2 和 v3 的地位是平等的，只是形式上有区别（就像 GitHub 的 v3 和 v4 API 一样，它们一个是 GraphQL，一个是 RESTful），我们就可以把它们想象成一个“后端里的后端”与两个不同版本的“后端里的前端”。像这样：

```
 Penguin V2
┌───────────────────┬──────────────┐
│ItemController(V2)◄│Item(EntityV2)◄─┐                      Penguin Core
└───────────────────┴──────────────┘ │ ┌────────────┬──────────┬────────┐
 Penguin V3                          ├─┤ItemService◄│ItemModel◄│ItemRepo│
┌───────────────────┬──────────────┐ │ └────────────┴──────────┴────────┘
│ItemController(V3)◄│Item(EntityV3)◄─┘
└───────────────────┴──────────────┘
```

**这样一来，公用的部分被我们全部放在了 Core 里。** 只不过缺点也很明显，就是会多一层抽象。

由于我并没有实际参与过 Penguin 的开发，所以不太确定这些解决方案能不能很好地涵盖企鹅的业务。或许把方案折中一下会更适合？

### 把模型分割成数据库模型和服务模型

另外，我注意到现在 Penguin 是把数据库模型和服务模型用一个 `struct` 来表示了。也就是说，Penguin 用一个 `struct` 承担了“从数据库反序列化到程序”和“从程序序列化到 JSON”的工作。这样做的坏处就是，不方便使 v2 和 v3 的 API 返回不同格式的数据，并且会使唯一存在的一个模型变得臃肿。

如果能把现在的模型分割成两个，分别服务于 Repo 和 Service-Controller （分别是我上面两张流程图的 ItemModel 和 ItemEntity），我们就能更方便地表达同一个数据的不同形式了。

**Comment by GalvinGao** [comment]
@FlandiaYingman 感谢回复~

事实上，对于未来的规划上，考虑到不对当前依赖企鹅物流 v2 API 的第三方业务产生过大影响，是期望将 v2 与 v3 共存存在的。除此之外，我个人也是更倾向于将核心部分抽象至 core 的，这样可以为以后可能的更多功能实现提供更多便利。

对于分离数据库与服务模型，我也是持支持意见的：现在的事实上算是懒省事的方法。将这两者解耦也可以大幅提升工程质量。

这样一来，我认为需要讨论的问题就已全部解决了。考虑到 refactor 会对 codebase 产生非常大的改动，因此在 refactor 完成之前，codebase 将基本无法进行任何业务开发。我争取在 48 小时内将所有 refactor 全部完成。

**Comment by FlandiaYingman** [comment]
@GalvinGao A well-designed structure can provide great convenience for future development. It's worth it to spend time on doing this perfect. So take your time, there's no hurry XD

**Comment by GalvinGao** [comment]
@FlandiaYingman I've decided to move the more idiomatic refactor (the categorize by responsibility approach) a bit more later than doing it now, to reduce the workload as well to catch up with predefined deadline of v3 API as well the `StatHouse` plan (tldr: a Penguin Statistics live gateway)

**Pull request merged**
